version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres_srv
    networks:
      - postgres_network

  postgres_srv:
    image: postgres:12
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/datas
    environment:
      POSTGRES_DB: jobs-list
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev123
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
    

