version: '3'
services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - ~/.aws/config:/root/.aws
    environment:
      POSTGRES_HOST: postgres_srv
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION
      AWS_S3_BUCKET: $AWS_S3_BUCKET
    depends_on:
      - postgres_srv
    networks:
      - postgres_network

  postgres_srv:
    container_name: postgres_srv
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    environment:
      POSTGRES_HOST: postgres_srv
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

networks:
  postgres_network:
    driver: bridge
    

