version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_HOST: postgres_srv
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      - postgres_srv
    networks:
      - postgres_network

  postgres_srv:
    image: postgres:12
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/datas
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
    

